application: phpne14
version: alpha1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /bootstrap\.min\.css
  static_files: public/bootstrap.min.css
  upload: public/bootstrap\.min\.css

- url: /search\.js
  static_files: public/search.js
  upload: public/search\.js

- url: /search
  script: public/search.php

- url: .*
  script: public/main.php
